version: "2"

services:
  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=project4
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=passw0rd
    ports:
      - 5433:5433
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    #command: tail -f /dev/null  # 保持容器运行
  proj4:
    container_name: proj4
    build: ./
    image: proj4:latest
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - 12345:12345
    volumes:
      - ./:/app
    depends_on:
      - postgres