version: "3"

services:
  eng:
    build: .
    volumes:
      - .:/app
    ports:
      - "12345:12345"
    depends_on:
      - db

  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"

